searchcode:
  image: quay.io/spivegin/searchcode
  volumes:
    - /srv/searchcode/index:/srv/index
    - /srv/searchcode/repo:/srv/repo
    - /srv/searchcode/searchcode.properties:/srv/searchcode.properties
    - /srv/searchcode/searchcode.sqlite:/srv/searchcode.sqlite
  ports:
    - "8080:8080/tcp"
